#pragma once
#include <windows.h>

namespace Color {
    inline void set(WORD color) {
        SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
    }
    inline void reset() {
        set(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE);
    }

    constexpr WORD WHITE  = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
    constexpr WORD BRIGHT = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
    constexpr WORD CYAN   = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
    constexpr WORD GREEN  = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
    constexpr WORD YELLOW = FOREGROUND_RED  | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
    constexpr WORD RED    = FOREGROUND_RED  | FOREGROUND_INTENSITY;
    constexpr WORD GRAY   = FOREGROUND_RED  | FOREGROUND_GREEN | FOREGROUND_BLUE;
    constexpr WORD BLUE   = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
}
